// Secrets are not declared in wrangler.jsonc (they are set with `wrangler secret put`), so the Env
// generated by `wrangler types` lacks them; add them here via declaration merging. The generated
// file defines both `Cloudflare.Env` and the global `Env` (the latter extends the former), so both
// must be merged; the `env` from `cloudflare:test` uses `Cloudflare.Env`.
interface CodexDataSecrets {
  REFRESH_TOKEN_KEK: string;
  ADMIN_TOKEN: string;
  SYNC_MODE?: string;
}

declare namespace Cloudflare {
  interface Env extends CodexDataSecrets {}
}

interface Env extends CodexDataSecrets {}
